version: '3.7'

services:
  web:
    build: .
    container_name: mtg_ai_assistant
    ports:
      - 8501:8501
    environment:
      - QDRANT_HOST=qdrant
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant:v1.2.2
    ports:
    - 6333:6333
    volumes:
      - /tmp/qdrant_storage:/qdrant/storage
